development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://h:pc8458deaad416a5fbabbe6830f68303746e4cab67adc84c81f2e17b98fd4d5e2@ec2-54-86-137-169.compute-1.amazonaws.com:7749
  :host: ec2-54-85-101-85.compute-1.amazonaws.com
  :port: 53679
  :password: p0ee4458bbafc025d1f8e5a99f54bd9580626fc51049bfa93e4f87cec3e45bfa9
  :inline: true
  :timeout: 1
